### ISSUE TITLE
CE is now looking for Table 'users_field_data' in the wrong database (when using separate Drupal/CiviCRM dbs)

### ISSUE THREAD

**Issue by KarinG** [eileenmcnaughton/civicrm_entity#313]
Problem/Motivation
----------------------------------------
After updating to the latest (git) - all our calendar views of activities (w/ relationship Assignee -> to Drupal users) are broken -> 
![image](https://user-images.githubusercontent.com/5340555/123293248-1164bc80-d4d1-11eb-96db-25a00aa879da.png)

Steps to reproduce
----------------------------------------
Create a View of Activities 
Add Relationships
Contact (Assignee)
(Contact (Assignee)) User -> observe error

Reverting back to this commit [where we were prior to this mornings git pull] -> fixes the issue
root@84b98158bcbb:/var/www/drupal/web/sites/default/modules/civicrm_entity# git checkout fc6c5779a239c65047eb2e98482c411225f46c71

Note: this is site with a separate drupal and civicrm database. Table 'users_field_data' does exist -> in the Drupal database.
Separate db-s is our default for upgraded from D7 sites.

**Comment by mglaman** [comment]
This had to be due to something with https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/Plugin/views/query/CivicrmSql.php#L62.

When we have the base table on a CiviCRM entity, it adds that connection info. But, for some reason, Views does not switch to the proper DB connection for a relationship... because Views probably doesn't work this way :( It's raw adding the JOIN.

So I don't think there is _any way possible_ for Views + CiviCRM Entity to work with a separate database without the prefix hack/workaround.

I'm going to do some quick digging into the core issue queue to see

**Comment by mglaman** [comment]
Good news! Maybe the bug is here: https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/Plugin/views/relationship/CiviCrmBridgeRelationshipBase.php

The relationship if Contact (assignee) -> User which _should_ be the `civicrm_entity_civicrm_contact_user` plugin.

**Comment by KarinG** [comment]
@mglaman -> so to make separate db-s work  - we do what we did in D7/CiviCRM - i.e. adding the CiviCRM tables to the settings.php file. 

```
$databases['default']['default']['prefix']= array(
  'default' => '',
  'civicrm_acl'                              => '`civicrm_sace`.',
  'civicrm_acl_cache'                        => '`civicrm_sace`.',
  'civicrm_acl_contact_cache'                => '`civicrm_sace`.',
...
```

And that works well when I go back and checkout commit -> 
`root@84b98158bcbb:/var/www/drupal/web/sites/default/modules/civicrm_entity# git checkout fc6c577`

**Comment by mglaman** [comment]
Test View that I created based off of data from @KarinG that I'm using for testing.

<img width="1306" alt="Screen Shot 2021-06-28 at 10 09 53 PM" src="https://user-images.githubusercontent.com/3698644/123731343-93e8d580-d85d-11eb-8957-e94c52c2095e.png">

Generated SQL – I don't have 2 databases set up, yet

```
SELECT civicrm_activity.id AS id, civicrm_contact_civicrm_activity_contact.id AS civicrm_contact_civicrm_activity_contact_id, users_field_data_civicrm_uf_match.uid AS users_field_data_civicrm_uf_match_uid
FROM
{civicrm_activity} civicrm_activity
LEFT JOIN {civicrm_activity_contact} civicrm_activity_contact ON civicrm_activity.id = civicrm_activity_contact.activity_id AND civicrm_activity_contact.record_type_id = '1'
LEFT JOIN {civicrm_contact} civicrm_contact_civicrm_activity_contact ON civicrm_activity_contact.contact_id = civicrm_contact_civicrm_activity_contact.id
LEFT JOIN {civicrm_uf_match} civicrm_contact_civicrm_activity_contact__civicrm_uf_match ON civicrm_contact_civicrm_activity_contact.id = civicrm_contact_civicrm_activity_contact__civicrm_uf_match.contact_id
LEFT JOIN {users_field_data} users_field_data_civicrm_uf_match ON civicrm_contact_civicrm_activity_contact__civicrm_uf_match.uf_id = users_field_data_civicrm_uf_match.uid
LIMIT 11 OFFSET 0
```

Export of the View config for anyone else

```
langcode: en
status: true
dependencies:
  module:
    - civicrm_entity
    - user
id: activity_contact_user_bug
label: 'Activity Contact User Bug'
module: views
description: ''
tag: ''
base_table: civicrm_activity
base_field: id
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 0
    display_options:
      access:
        type: none
        options: {  }
      cache:
        type: tag
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: false
          distinct: false
          replica: false
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: mini
        options:
          items_per_page: 10
          offset: 0
          id: 0
          total_pages: null
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      style:
        type: default
        options:
          grouping: {  }
          row_class: ''
          default_row_class: true
          uses_fields: false
      row:
        type: fields
        options:
          inline: {  }
          separator: ''
          hide_empty: false
          default_field_elements: true
      fields:
        subject:
          table: civicrm_activity
          field: subject
          id: subject
          entity_type: null
          entity_field: subject
          plugin_id: field
          relationship: none
          group_type: group
          admin_label: ''
          label: ''
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings: {  }
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
      filters: {  }
      sorts: {  }
      header: {  }
      footer: {  }
      empty: {  }
      relationships:
        contact:
          id: contact
          table: civicrm_activity
          field: contact
          relationship: none
          group_type: group
          admin_label: 'Contact (Assignee)'
          required: false
          record_type_id: '1'
          entity_type: civicrm_activity
          plugin_id: civicrm_entity_activity_contact
        user:
          id: user
          table: civicrm_contact
          field: user
          relationship: contact
          group_type: group
          admin_label: User
          required: false
          entity_type: civicrm_contact
          plugin_id: civicrm_entity_civicrm_contact_user
      arguments: {  }
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url.query_args
      tags: {  }
```
